### ISSUE TITLE
Could you please release the Matlab version of the code?

### ISSUE THREAD

**Issue by rfwaefd** [JoshuaTetzner/FDTD_PML#1]

**Comment by JoshuaTetzner** [comment]
I do not have a Matlab version of the code and I will not rewrite the code. There is a Matlab version of the FDTD PML published with the Davidson book (https://www.cambridge.org/us/academic/subjects/engineering/rf-and-microwave-engineering/computational-electromagnetics-rf-and-microwave-engineering-2nd-edition?format=HB&isbn=9780521518918). You finde the Matlab files under Resources/Software. I used this code as basis, but noticed some errors. My Julia code is optimized and corrected.
